### ISSUE TITLE
feature request make window dark??

### ISSUE THREAD

**Issue by jjfmz42015** [Speedvicio/MedGuiReborn#7]
feature request make window dark??

ie you can currently recolor grid area but outside of that rest is always grey, have a dark mode to change that color to dark or even color options?

Would be nice.

**Comment by Speedvicio** [comment]
The code to make the frontend customizable is already in, the result is not good due to limitations on winform, for example in tab control the only one propriety that you can change is the beckgroud color but the tabs will remain as is.
Better result can be done using wpf but this require a entire recode of all.
Next release will have the option to change colors enabled, but t is highly recommended to leave the frontend as it is.

**Comment by Speedvicio** [comment]
This is a early beta with support to custom color, you can try it.

[MedGuiR.zip](https://github.com/Speedvicio/MedGuiReborn/files/3791086/MedGuiR.zip)

**Comment by jjfmz42015** [comment]
Ok. I see. Thanks for the beta I will take it for a spin and report back.

Thanks for this nice front end btw

**Comment by Speedvicio** [comment]
I had forgotten to attach the icon for the themes menu, without which you would receive a missing resources error.

[MedGuiR.zip](https://github.com/Speedvicio/MedGuiReborn/files/3792610/MedGuiR.zip)

**Comment by Speedvicio** [comment]
Added on [v0.109](https://github.com/Speedvicio/MedGuiReborn/releases/tag/v0.109)
